/**
 * PNG encoder (RGBA 8-bit only)
 *
 * Outputs raster images generated by SVG filters etc. as a PNG byte sequence.
 */

import { zlibDeflate } from '../compression/deflate.js'

const PNG_SIGNATURE = new Uint8Array([137, 80, 78, 71, 13, 10, 26, 10])

const CRC32_TABLE = (() => {
  const table = new Uint32Array(256)
  for (let i = 0; i < 256; i++) {
    let c = i
    for (let j = 0; j < 8; j++) {
      c = (c & 1) ? (0xEDB88320 ^ (c >>> 1)) : (c >>> 1)
    }
    table[i] = c >>> 0
  }
  return table
})()

function crc32(data: Uint8Array): number {
  let crc = 0xFFFFFFFF
  for (let i = 0; i < data.length; i++) {
    crc = CRC32_TABLE[(crc ^ data[i]!) & 0xFF]! ^ (crc >>> 8)
  }
  return (crc ^ 0xFFFFFFFF) >>> 0
}

function writeUint32BE(out: Uint8Array, pos: number, v: number): void {
  out[pos] = (v >>> 24) & 0xFF
  out[pos + 1] = (v >>> 16) & 0xFF
  out[pos + 2] = (v >>> 8) & 0xFF
  out[pos + 3] = v & 0xFF
}

function makeChunk(type: string, data: Uint8Array): Uint8Array {
  const out = new Uint8Array(12 + data.length)
  writeUint32BE(out, 0, data.length >>> 0)
  out[4] = type.charCodeAt(0)
  out[5] = type.charCodeAt(1)
  out[6] = type.charCodeAt(2)
  out[7] = type.charCodeAt(3)
  out.set(data, 8)

  const crcInput = new Uint8Array(4 + data.length)
  crcInput[0] = out[4]!
  crcInput[1] = out[5]!
  crcInput[2] = out[6]!
  crcInput[3] = out[7]!
  crcInput.set(data, 4)
  writeUint32BE(out, 8 + data.length, crc32(crcInput))
  return out
}

/**
 * Encode an RGBA (8-bit) pixel sequence as a PNG.
 */
export function encodePngRgba(width: number, height: number, rgba: Uint8Array): Uint8Array {
  if (!(width > 0) || !(height > 0)) {
    throw new Error('PNG encoder: width/height must be positive')
  }
  if (rgba.length !== width * height * 4) {
    throw new Error('PNG encoder: invalid RGBA buffer length')
  }

  const rowBytes = width * 4
  const raw = new Uint8Array((rowBytes + 1) * height)
  let srcPos = 0
  let dstPos = 0
  for (let y = 0; y < height; y++) {
    raw[dstPos++] = 0 // Filter: None
    raw.set(rgba.subarray(srcPos, srcPos + rowBytes), dstPos)
    dstPos += rowBytes
    srcPos += rowBytes
  }

  const ihdr = new Uint8Array(13)
  writeUint32BE(ihdr, 0, width >>> 0)
  writeUint32BE(ihdr, 4, height >>> 0)
  ihdr[8] = 8  // bit depth
  ihdr[9] = 6  // color type: RGBA
  ihdr[10] = 0 // compression
  ihdr[11] = 0 // filter
  ihdr[12] = 0 // interlace

  const idat = zlibDeflate(raw)
  const chunks = [
    PNG_SIGNATURE,
    makeChunk('IHDR', ihdr),
    makeChunk('IDAT', idat),
    makeChunk('IEND', new Uint8Array(0)),
  ]

  let total = 0
  for (let i = 0; i < chunks.length; i++) total += chunks[i]!.length
  const out = new Uint8Array(total)
  let pos = 0
  for (let i = 0; i < chunks.length; i++) {
    out.set(chunks[i]!, pos)
    pos += chunks[i]!.length
  }
  return out
}

