import { execFileSync } from 'node:child_process'
import { mkdtempSync, readFileSync, rmSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'
import { decryptPkcs8PrivateKey } from '../../src/encryption/pkcs8.js'

function bytes(path: string): Uint8Array {
  const value = readFileSync(path)
  return new Uint8Array(value.buffer, value.byteOffset, value.byteLength)
}

describe('RFC 8018 encrypted PKCS#8', function () {
  it('decrypts the PBES2 cipher and PBKDF2 PRF matrix generated by an independent implementation', function () {
    const directory = mkdtempSync(join(tmpdir(), 'tsreport-pkcs8-'))
    try {
      const keyPem = join(directory, 'key.pem')
      const plainDer = join(directory, 'plain.der')
      execFileSync('openssl', ['genpkey', '-algorithm', 'RSA', '-pkeyopt', 'rsa_keygen_bits:1024', '-out', keyPem], { stdio: 'ignore' })
      execFileSync('openssl', ['pkcs8', '-topk8', '-nocrypt', '-in', keyPem, '-outform', 'DER', '-out', plainDer])
      const expected = bytes(plainDer)
      const ciphers = ['aes-128-cbc', 'aes-192-cbc', 'aes-256-cbc', 'des3'] as const
      const prfs = ['hmacWithSHA1', 'hmacWithSHA224', 'hmacWithSHA256', 'hmacWithSHA384', 'hmacWithSHA512'] as const
      for (let cipherIndex = 0; cipherIndex < ciphers.length; cipherIndex++) {
        for (let prfIndex = 0; prfIndex < prfs.length; prfIndex++) {
          const encryptedDer = join(directory, `${cipherIndex}-${prfIndex}.der`)
          execFileSync('openssl', [
            'pkcs8', '-topk8', '-in', keyPem, '-outform', 'DER', '-out', encryptedDer,
            '-v2', ciphers[cipherIndex]!, '-v2prf', prfs[prfIndex]!, '-iter', '17', '-passout', 'pass:帳票-password',
          ], { stdio: 'ignore' })
          expect(decryptPkcs8PrivateKey(bytes(encryptedDer), '帳票-password')).toEqual(expected)
          // A wrong key normally fails PKCS#7 padding, but random plaintext has
          // valid padding with non-zero probability and is then rejected by
          // the mandatory DER validation. Both are correct PBES2 rejection.
          expect(function () { return decryptPkcs8PrivateKey(bytes(encryptedDer), 'wrong-password') }).toThrow(/^PKCS#8:/)
        }
      }
    } finally {
      rmSync(directory, { recursive: true, force: true })
    }
  }, 30_000)
})
