import { describe, expect, it } from 'vitest'
import { Font } from '../src/index.js'

// Graphite2's MIT/LGPL/MPL test font. It contains a compact Silf VM program
// whose `ab` rule replaces two input slots with glyph 5.
const GRAPHITE_TEST_FONT = 'AAEAAAAOAIAAAwBgRmVhdIADgRkAAASwAAAAHEdsYXQFnAN1AAAEzAAAADZHbG9jAJMAfgAABQQAAAAaT1MvMlIAXDAAAAFoAAAAVlNpbGbZtvxrAAAFIAAAAVpTaWxsgIGAlAAABnwAAAAUY21hcAEvAWkAAAHYAAABFmdseWYSGHDjAAADAAAAAYBoZWFk5CRPggAAAOwAAAA2aGhlYQWRAS8AAAEkAAAAJGhtdHgIxQCDAAABwAAAABhsb2NhATIAuwAAAvAAAAAObWF4cAARADUAAAFIAAAAIHBvc3QADQFeAAAEgAAAAC8AAQAAAAEAACTqlKhfDzz1AAID6AAAAACwMy18AAAAANL63j3//P/xAeQC+AAAAAMAAgAAAAAAAAABAAADr/8fAAACCP/8AAEB5AABAAAAAAAAAAAAAAAAAAAABgABAAAABgA1AAIAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAEBzwGQAAUAAAK8AooAAACPArwCigAAAcUAMgEDAAAAAAQAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAE1BQ1IAQAAgAGMDr/8fAAADrwDhAAAAAAAAAAAAAAH0AD8AAAAAASwAAAHOACUCCP/8Ac4AIwAAAAMAAAAAAAAAHAABAAAAAABEAAMAAQAAABwABAAoAAAABgAEAAEAAgAgAGP//wAAACAAYf///+L/ogABAAAAAAAAAAYA0gAAAAAAZAABAAAAAAAAAAAAAAAAAAAAAQACAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMABAAFAAAAAAATABMAEwBfAJUAwAAAAAIAPwAAAbYC+AADAAcAADMRIRElMxEjPwF3/sf6+gL4/Qg/AnsAAgAl//cBzQHeACoANAAAJQYjIjUGBwYjIiY1NDc2NzU0JiMiBgcXFiMiNTQ3NjMyFxYVFRQXFjMyNyc1BgcGFRQWFxYBzTk2NkAWGyMyPS85myotHyUCAQIsKzQwRl4jGwMEEg4ppWwlHCkeJkNMTDIMDkE2OScxNRNBOCAZHjAxNSAfKyFSnzwVGSkEsiokGyckMAEBAAAC//z/8QHkAtIAFQAhAAAlFAYjIicRNCcmJyYHJzczETYzMhcWBzQmIyIHERYzMjc2AeSOYlFYAwMKDioHjBhETkozNVhMNzA5MzsxJSj7cZk8AeFKFxIIDA0SOP6vXTxAhFVkNv7pMzI4AAABACP/8QGrAd4AHAAAJQYGIyImNTQ3NjMyFxYVFCMiJiMiBhUUFxYzMjcBqw1wRVRyQj9dNTE4MDMKQjhCJypGXzGxVGyIb2xGRBwhMit5X0pXO0B2AAIAAAAAAAD/ewAUAAAAAAAAAAAAAAAAAAAAAAAAAAAABgECAAAAAwBEAEUARgAAAAEAAAABAAAAAAAAAAEAAAAAABiAAAECAAB//wABAAABAgADAB4BAgADAB4BAwADAA8ACQECAAIAHgECAAMAHgECAAEAHgECAAMAHgECAAMAHgAAAAEAAAAAAAgABAAKABAAGAAeACQAKgAwADYAAAACAAAAAQAAAAAADAAHAAAAAAIAAQH/BAAAAAIDBAEAAAAAAAEAAAAAAAAAAAYAAABEAAAA1wAAAU4AAAAAAAAAAAACAAIACgAMAA4ABQADAAUDAAACAAAAAADIAAAAyAAAAMkAAAAAAAYABQACAAMABAAEAAIAAAAAAAIAAAADAAMAAQAEAAQAAgAFAAcAAAAAAAEAAgABAAAAAQAAAAEAAgACAAEAAAAAAAAAAAEAAAAKAA4AAQABAAIAAAADAAAAAAAEAAAAAAAAAAUAAAAAAAUAABwAIQIAARkgGTEcABkxAAUCAAABAAAAAAEsAAABLAAAAS0AAAAAAAMAAgABAAIAAgACAAEAAAADAAMAAAAFAAUAAQAAAAEAAAAAAAAAAgAKAAAAAAABAAAAIQABAAAAAAACAAAbHgAB/yYCAQAjESkGACMIKQcAIwksBgAjAywHACMEGTEAAAABAAAAAAAAAAAAAICAgIAAAAAU'

function loadGraphiteTestFont(): Font {
  // Keep the long all-zero glyph-directory span separate so formatters do not
  // turn the already-long fixture line into an impractical source line.
  const encoded = GRAPHITE_TEST_FONT.slice(0, 962) + 'A'.repeat(32) + GRAPHITE_TEST_FONT.slice(962)
  const bytes = Uint8Array.from(atob(encoded), function (character) { return character.charCodeAt(0) })
  return Font.load(bytes.buffer)
}

describe('Graphite shaping VM', function () {
  it('connects Silf rule execution to Font.shapeText', function () {
    const font = loadGraphiteTestFont()
    expect(font.silf).not.toBeNull()
    expect(font.shapeText('ab').map(function (glyph) { return glyph.glyphId })).toEqual([5])
  })

  it('continues the pass after a multi-slot replacement', function () {
    const font = loadGraphiteTestFont()
    const shaped = font.shapeText('abc')
    expect(shaped.map(function (glyph) { return glyph.glyphId })).toEqual([5, 5])
    expect(shaped.map(function (glyph) { return glyph.xAdvance })).toEqual([462, 462])
  })
})
