/**
 * External PDF merge feature tests (parser + page import + merge).
 *
 * - Inputs generated by our own PdfBackend (xref stream + ObjStm / classic xref / encrypted)
 * - Hand-built inputs (xref stream with PNG predictor / incremental update / inherited attributes)
 * - Merge results are re-parsed with our own parser for round-trip verification
 */
import { describe, it, expect, beforeAll } from 'vitest'
import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { Font } from '../../src/font.js'
import { PdfBackend } from '../../src/renderer/pdf-backend.js'
import { render } from '../../src/renderer/renderer.js'
import type { RenderDocument } from '../../src/types/render.js'
import { zlibDeflate } from '../../src/compression/deflate.js'
import { mergePdfFiles, collectPdfPages } from '../../src/pdf/pdf-import.js'
import { parsePdf, PdfName, PdfRef, PdfStream } from '../../src/pdf/pdf-parser.js'
import { PdfImporter } from '../../src/pdf/pdf-page-importer.js'
import { createEncryptionContext } from '../../src/renderer/pdf-encryption.js'
import { pdfToText } from '../renderer/pdf-test-utils.js'

const FIXTURES = join(__dirname, '..', 'fixtures', 'fonts')

let font: Font

beforeAll(() => {
  const buf = readFileSync(join(FIXTURES, 'Roboto-Regular.ttf'))
  font = Font.load(buf.buffer as ArrayBuffer)
})

// ─── Test PDF generation helpers ───

function latin1(bytes: Uint8Array): string {
  return new TextDecoder('latin1').decode(bytes)
}

function enc(s: string): Uint8Array {
  const bytes = new Uint8Array(s.length)
  for (let i = 0; i < s.length; i++) bytes[i] = s.charCodeAt(i) & 0xFF
  return bytes
}

function concat(parts: Uint8Array[]): Uint8Array {
  let total = 0
  for (const p of parts) total += p.length
  const out = new Uint8Array(total)
  let pos = 0
  for (const p of parts) {
    out.set(p, pos)
    pos += p.length
  }
  return out
}

function buildBinaryObjectsPdf(objects: Uint8Array[], trailerEntries = ''): Uint8Array {
  const header = enc('%PDF-1.7\n')
  let offset = header.length
  const offsets: number[] = [0]
  for (let i = 0; i < objects.length; i++) {
    offsets.push(offset)
    offset += objects[i]!.length
  }
  const xrefOffset = offset
  let xref = `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`
  for (let i = 1; i < offsets.length; i++) {
    xref += `${String(offsets[i]!).padStart(10, '0')} 00000 n \n`
  }
  const trailer = `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R ${trailerEntries} >>\nstartxref\n${xrefOffset}\n%%EOF\n`
  return concat([header, ...objects, enc(xref), enc(trailer)])
}

/** Builds minimal JPEG data (equivalent to tests/renderer/pdf-image.test.ts) */
function createMinimalJpeg(width: number, height: number, components: number): Uint8Array {
  const data: number[] = []
  data.push(0xFF, 0xD8)
  const sofLen = 8 + components * 3
  data.push(0xFF, 0xC0)
  data.push((sofLen >> 8) & 0xFF, sofLen & 0xFF)
  data.push(8)
  data.push((height >> 8) & 0xFF, height & 0xFF)
  data.push((width >> 8) & 0xFF, width & 0xFF)
  data.push(components)
  for (let i = 0; i < components; i++) data.push(i + 1, 0x11, 0)
  data.push(0xFF, 0xDA)
  data.push(0x00, 0x02 + components * 2 + 1)
  data.push(components)
  for (let i = 0; i < components; i++) data.push(i + 1, 0x00)
  data.push(0x00, 0x3F, 0x00)
  data.push(0xFF, 0xD9)
  return new Uint8Array(data)
}

/** Two-page PDF with text + shapes (default output = xref stream + ObjStm) */
function makeTextPdf(): Uint8Array {
  const backend = new PdfBackend({ fonts: { default: font } })
  const doc: RenderDocument = {
    pages: [
      {
        width: 595, height: 842,
        children: [
          { type: 'text', x: 72, y: 72, text: 'Hello Merge', fontId: 'default', fontSize: 14, color: '#000000' },
          { type: 'rect', x: 50, y: 120, width: 200, height: 80, fill: '#ff0000', stroke: '#0000ff' },
        ],
      },
      {
        width: 595, height: 842,
        children: [
          { type: 'text', x: 72, y: 72, text: 'Page Two', fontId: 'default', fontSize: 12, color: '#333333' },
        ],
      },
    ],
  }
  render(doc, backend)
  // Internal link from page 1 to page 2 (used to verify page reference remapping)
  backend.addAnnotation(0, { type: 'localPage', target: '2', x: 72, y: 60, width: 100, height: 20 })
  return backend.toUint8Array()
}

function makeEncryptedTextPdf(method: 'rc4-128' | 'aes-128' | 'aes-256'): Uint8Array {
  const backend = new PdfBackend({
    fonts: { default: font },
    encryption: {
      userPassword: 'secret',
      ownerPassword: 'owner',
      method,
    },
  })
  const doc: RenderDocument = {
    pages: [{
      width: 595, height: 842,
      children: [
        { type: 'text', x: 72, y: 72, text: 'Encrypted Merge', fontId: 'default', fontSize: 14, color: '#000000' },
        { type: 'line', x1: 72, y1: 100, x2: 240, y2: 100, lineWidth: 1, color: '#0055aa' },
      ],
    }],
  }
  render(doc, backend)
  return backend.toUint8Array()
}

function makeCustomCryptFilterPdf(): Uint8Array {
  const context = createEncryptionContext({
    userPassword: 'secret',
    ownerPassword: 'owner',
    method: 'aes-128',
  })
  const plain = enc('0 0 m 100 50 l S\n')
  const encrypted = context.encryptStream(4, 0, plain)
  const encryptDict = context.encryptDict.map(line => {
    if (line.startsWith('/CF ')) return '/CF << /MyCF << /CFM /AESV2 /AuthEvent /DocOpen /Length 16 >> >>'
    if (line === '/StmF /StdCF') return '/StmF /Identity'
    if (line === '/StrF /StdCF') return '/StrF /Identity'
    if (line === '/EFF /StdCF') return '/EFF /Identity'
    return line
  }).join(' ')
  const objects = [
    enc('1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n'),
    enc('2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj\n'),
    enc('3 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 100 100] /Resources << >> /Contents 4 0 R >>\nendobj\n'),
    concat([
      enc(`4 0 obj\n<< /Length ${encrypted.length} /Filter /Crypt /DecodeParms << /Name /MyCF >> >>\nstream\n`),
      encrypted,
      enc('\nendstream\nendobj\n'),
    ]),
    enc(`5 0 obj\n<< ${encryptDict} >>\nendobj\n`),
  ]
  return buildBinaryObjectsPdf(objects, `/Encrypt 5 0 R /ID [<${context.fileId}> <${context.fileId}>]`)
}

function buildTiffPredictorContentPdf(
  encodedContent: Uint8Array,
  options: { colors: number; bitsPerComponent: number; columns: number },
): Uint8Array {
  const compressed = zlibDeflate(encodedContent)
  const objects = [
    enc('1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n'),
    enc('2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj\n'),
    enc('3 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 100 100] /Resources << >> /Contents 4 0 R >>\nendobj\n'),
    concat([
      enc(
        `4 0 obj\n<< /Length ${compressed.length} /Filter /FlateDecode`
        + ` /DecodeParms << /Predictor 2 /Colors ${options.colors}`
        + ` /BitsPerComponent ${options.bitsPerComponent} /Columns ${options.columns} >> >>\nstream\n`,
      ),
      compressed,
      enc('\nendstream\nendobj\n'),
    ]),
  ]
  return buildBinaryObjectsPdf(objects)
}

function buildPngPredictorContentPdf(encodedContent: Uint8Array, columns: number): Uint8Array {
  const compressed = zlibDeflate(encodedContent)
  const objects = [
    enc('1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n'),
    enc('2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj\n'),
    enc('3 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 100 100] /Resources << >> /Contents 4 0 R >>\nendobj\n'),
    concat([
      enc(
        `4 0 obj\n<< /Length ${compressed.length} /Filter /FlateDecode`
        + ` /DecodeParms << /Predictor 15 /Colors 1 /BitsPerComponent 8 /Columns ${columns} >> >>\nstream\n`,
      ),
      compressed,
      enc('\nendstream\nendobj\n'),
    ]),
  ]
  return buildBinaryObjectsPdf(objects)
}

function buildLzwContentPdf(encodedContent: Uint8Array, decodeParms: string): Uint8Array {
  const objects = [
    enc('1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n'),
    enc('2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj\n'),
    enc('3 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 100 100] /Resources << >> /Contents 4 0 R >>\nendobj\n'),
    concat([
      enc(`4 0 obj\n<< /Length ${encodedContent.length} /Filter /LZWDecode ${decodeParms} >>\nstream\n`),
      encodedContent,
      enc('\nendstream\nendobj\n'),
    ]),
  ]
  return buildBinaryObjectsPdf(objects)
}

function lzwEncode(data: Uint8Array, earlyChange: 0 | 1): Uint8Array {
  const dictionary = new Map<string, number>()
  for (let i = 0; i < 256; i++) dictionary.set(String.fromCharCode(i), i)
  let nextCode = 258
  let codeSize = 9
  let current = ''
  const writer = new TestLzwBitWriter()
  writer.write(256, codeSize)
  for (let i = 0; i < data.length; i++) {
    const char = String.fromCharCode(data[i]!)
    const joined = current + char
    if (dictionary.has(joined)) {
      current = joined
      continue
    }
    writer.write(dictionary.get(current)!, codeSize)
    if (nextCode < 4096) {
      dictionary.set(joined, nextCode)
      nextCode++
      if (nextCode > (1 << codeSize) - earlyChange && codeSize < 12) codeSize++
    }
    current = char
  }
  if (current.length > 0) writer.write(dictionary.get(current)!, codeSize)
  writer.write(257, codeSize)
  return writer.toUint8Array()
}

class TestLzwBitWriter {
  private readonly bytes: number[] = []
  private bitPos = 0

  write(code: number, bits: number): void {
    for (let bit = bits - 1; bit >= 0; bit--) {
      if (((code >> bit) & 1) !== 0) {
        const index = this.bitPos >> 3
        this.bytes[index] = (this.bytes[index] ?? 0) | (1 << (7 - (this.bitPos & 7)))
      }
      this.bitPos++
    }
  }

  toUint8Array(): Uint8Array {
    return new Uint8Array(this.bytes)
  }
}

/** One-page PDF with a JPEG image + a line */
function makeImagePdf(): Uint8Array {
  const backend = new PdfBackend({ fonts: {} })
  const doc: RenderDocument = {
    pages: [{
      width: 400, height: 300,
      children: [
        { type: 'image', x: 20, y: 20, width: 100, height: 80, imageId: 'photo' },
        { type: 'line', x1: 0, y1: 0, x2: 400, y2: 300, lineWidth: 2, color: '#00ff00' },
      ],
    }],
    images: { photo: createMinimalJpeg(8, 8, 3) },
  }
  render(doc, backend)
  return backend.toUint8Array()
}

/** One-page PDF with a classic xref table (PDF/A-1b output) */
function makeClassicXrefPdf(): Uint8Array {
  const backend = new PdfBackend({ fonts: {}, pdfaConformance: 'PDF/A-1b' })
  const doc: RenderDocument = {
    pages: [{
      width: 500, height: 500,
      children: [
        { type: 'rect', x: 10, y: 10, width: 480, height: 480, stroke: '#000000' },
      ],
    }],
  }
  render(doc, backend)
  return backend.toUint8Array()
}

/**
 * Hand-built PDF: xref stream with PNG predictor (Predictor 12 = Up).
 * MediaBox / Rotate / Resources live only on the Pages node to exercise inheritance resolution.
 */
function buildPredictorXrefPdf(): Uint8Array {
  const parts: Uint8Array[] = []
  let offset = 0
  const push = (b: Uint8Array): number => {
    const at = offset
    parts.push(b)
    offset += b.length
    return at
  }

  push(enc('%PDF-1.5\n'))
  const off1 = push(enc('1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n'))
  const off2 = push(enc(
    '2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1'
    + ' /MediaBox [0 0 200 100] /Rotate 90 /Resources << /ProcSet [/PDF] >> >>\nendobj\n',
  ))
  const off3 = push(enc('3 0 obj\n<< /Type /Page /Parent 2 0 R /Contents 4 0 R >>\nendobj\n'))
  const content = '0 0 m 100 50 l S'
  const off4 = push(enc(`4 0 obj\n<< /Length ${content.length} >>\nstream\n${content}\nendstream\nendobj\n`))

  // xref stream (object 5): W [1 4 2], PNG Up predictor (filter type 2)
  const xrefStreamOffset = offset
  const offsets = [0, off1, off2, off3, off4, xrefStreamOffset]
  const rowLen = 7
  const raw = new Uint8Array(6 * rowLen)
  for (let i = 0; i < 6; i++) {
    const off = offsets[i]!
    raw[i * rowLen] = i === 0 ? 0 : 1 // type
    raw[i * rowLen + 1] = (off >> 24) & 0xFF
    raw[i * rowLen + 2] = (off >> 16) & 0xFF
    raw[i * rowLen + 3] = (off >> 8) & 0xFF
    raw[i * rowLen + 4] = off & 0xFF
    // field2: gen 65535 for the free entry (object 0), gen 0 for the rest
    raw[i * rowLen + 5] = i === 0 ? 0xFF : 0
    raw[i * rowLen + 6] = i === 0 ? 0xFF : 0
  }
  // Encode with the PNG Up predictor: encoded[i] = raw[i] - prevRow[i]
  const encoded = new Uint8Array(6 * (rowLen + 1))
  for (let r = 0; r < 6; r++) {
    encoded[r * (rowLen + 1)] = 2 // filter type Up
    for (let i = 0; i < rowLen; i++) {
      const prev = r > 0 ? raw[(r - 1) * rowLen + i]! : 0
      encoded[r * (rowLen + 1) + 1 + i] = (raw[r * rowLen + i]! - prev) & 0xFF
    }
  }
  const compressed = zlibDeflate(encoded)
  push(enc(
    `5 0 obj\n<< /Type /XRef /Size 6 /W [1 4 2] /Root 1 0 R /Filter /FlateDecode`
    + ` /DecodeParms << /Predictor 12 /Colors 1 /BitsPerComponent 8 /Columns ${rowLen} >>`
    + ` /Length ${compressed.length} >>\nstream\n`,
  ))
  push(compressed)
  push(enc('\nendstream\nendobj\n'))
  push(enc(`startxref\n${xrefStreamOffset}\n%%EOF\n`))

  return concat(parts)
}

/**
 * Hand-built PDF: classic xref + incremental update.
 * The updated revision (0 0 1 RG) overrides the initial content (1 0 0 RG).
 */
function buildIncrementalUpdatePdf(): Uint8Array {
  const parts: Uint8Array[] = []
  let offset = 0
  const push = (b: Uint8Array): number => {
    const at = offset
    parts.push(b)
    offset += b.length
    return at
  }

  push(enc('%PDF-1.4\n'))
  const off1 = push(enc('1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n'))
  const off2 = push(enc('2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj\n'))
  const off3 = push(enc(
    '3 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 300 300]'
    + ' /Resources << >> /Contents 4 0 R >>\nendobj\n',
  ))
  const contentV1 = '1 0 0 RG 0 0 m 10 10 l S'
  const off4 = push(enc(`4 0 obj\n<< /Length ${contentV1.length} >>\nstream\n${contentV1}\nendstream\nendobj\n`))

  // Initial revision xref
  const xref1 = push(enc(
    'xref\n0 5\n'
    + '0000000000 65535 f \n'
    + `${off1.toString().padStart(10, '0')} 00000 n \n`
    + `${off2.toString().padStart(10, '0')} 00000 n \n`
    + `${off3.toString().padStart(10, '0')} 00000 n \n`
    + `${off4.toString().padStart(10, '0')} 00000 n \n`
    + 'trailer\n<< /Size 5 /Root 1 0 R >>\nstartxref\n',
  ))
  push(enc(`${xref1}\n%%EOF\n`))

  // Incremental update: replaces object 4
  const contentV2 = '0 0 1 RG 0 0 m 20 20 l S'
  const off4v2 = push(enc(`4 0 obj\n<< /Length ${contentV2.length} >>\nstream\n${contentV2}\nendstream\nendobj\n`))
  const xref2 = push(enc(
    'xref\n4 1\n'
    + `${off4v2.toString().padStart(10, '0')} 00000 n \n`
    + `trailer\n<< /Size 5 /Root 1 0 R /Prev ${xref1} >>\nstartxref\n`,
  ))
  push(enc(`${xref2}\n%%EOF\n`))

  return concat(parts)
}

// ─── Tests ───

describe('mergePdfFiles', () => {
  // Verifies merging two xref-stream+ObjStm PDFs sums the page count and carries over content, fonts, and images.
  it('xref stream + ObjStm 形式の生成 PDF 同士を連結し、ページ数が合計になる', () => {
    const a = makeTextPdf()
    const b = makeImagePdf()

    // Confirm the inputs really are xref stream + ObjStm form (proves the supported range)
    expect(latin1(a)).toContain('/Type /XRef')
    expect(latin1(a)).toContain('/Type /ObjStm')

    const merged = mergePdfFiles([a, b])

    // Round-trip verification with our own parser
    const doc = parsePdf(merged)
    const pages = collectPdfPages(doc)
    expect(pages.length).toBe(3)

    // Each page: Contents exists as a stream and MediaBox is explicit
    for (const page of pages) {
      const contents = doc.resolve(page.dict.get('Contents') ?? null)
      expect(contents).toBeInstanceOf(PdfStream)
      const mediaBox = doc.resolve(page.dict.get('MediaBox') ?? null)
      expect(Array.isArray(mediaBox)).toBe(true)
      expect((mediaBox as unknown[]).length).toBe(4)
    }

    // Page sizes are preserved in the source PDF order
    const mb3 = doc.resolve(pages[2]!.dict.get('MediaBox') ?? null) as number[]
    expect(mb3[2]).toBe(400)
    expect(mb3[3]).toBe(300)

    // Content: text drawing, fonts, and images are carried over
    const text = pdfToText(merged)
    expect(text).toContain('Tj')
    expect(text).toContain('/Subtype /Type0')
    expect(text).toContain('/Subtype /Image')
    expect(text).toContain('/DCTDecode')
    expect(text).toContain('Do')

    // Exactly one new Catalog and Pages tree (old trees are not dragged in)
    expect(text.match(/\/Type \/Catalog/g)!.length).toBe(1)
    expect(text.match(/\/Type \/Pages/g)!.length).toBe(1)
  })

  // Verifies that a link annotation's /Dest page reference is remapped to the merged document's page object.
  it('ページ間リンク (/Annots) の参照先ページが付け替えられる', () => {
    const merged = mergePdfFiles([makeTextPdf(), makeImagePdf()])
    const doc = parsePdf(merged)
    const pages = collectPdfPages(doc)

    const annots = doc.resolve(pages[0]!.dict.get('Annots') ?? null)
    expect(Array.isArray(annots)).toBe(true)
    const annot = doc.resolve((annots as PdfRef[])[0]!)
    expect(annot).toBeInstanceOf(Map)
    const subtype = (annot as Map<string, unknown>).get('Subtype') as PdfName
    expect(subtype.name).toBe('Link')

    // The /Dest target points at the merged document's second page object
    const dest = doc.resolve((annot as Map<string, PdfRef>).get('Dest')!) as PdfRef[]
    expect(Array.isArray(dest)).toBe(true)
    expect(dest[0]).toBeInstanceOf(PdfRef)
    expect((dest[0] as PdfRef).num).toBe(pages[1]!.ref.num)
  })

  // Verifies that a classic-xref-table input (PDF/A-1b output) can be merged with a modern-format PDF.
  it('クラシック xref テーブル入力 (PDF/A-1b 出力) をマージできる', () => {
    const classic = makeClassicXrefPdf()
    expect(latin1(classic)).toContain('xref\n0 ')
    expect(latin1(classic)).toContain('trailer')

    const merged = mergePdfFiles([classic, makeImagePdf()])
    const doc = parsePdf(merged)
    expect(collectPdfPages(doc).length).toBe(2)

    const text = pdfToText(merged)
    expect(text).toContain(' re')       // rectangle drawing operator
    expect(text).toContain('/DCTDecode') // image
  })

  // Verifies PNG-predictor xref streams parse and inherited Pages attributes become explicit on the imported page.
  it('PNG predictor 付き xref stream を読み、継承属性をページへ明示化する', () => {
    const input = buildPredictorXrefPdf()

    // Input stage: the page itself has no MediaBox/Rotate/Resources
    const srcDoc = parsePdf(input)
    const srcPages = collectPdfPages(srcDoc)
    expect(srcPages.length).toBe(1)
    expect(srcPages[0]!.dict.has('MediaBox')).toBe(false)

    const merged = mergePdfFiles([input])
    const doc = parsePdf(merged)
    const pages = collectPdfPages(doc)
    expect(pages.length).toBe(1)

    // The merged page dict now carries the inherited attributes explicitly
    const pageDict = pages[0]!.dict
    const mediaBox = doc.resolve(pageDict.get('MediaBox') ?? null) as number[]
    expect(mediaBox).toEqual([0, 0, 200, 100])
    expect(doc.resolve(pageDict.get('Rotate') ?? null)).toBe(90)
    const resources = doc.resolve(pageDict.get('Resources') ?? null)
    expect(resources).toBeInstanceOf(Map)

    // The content stream is carried over as well
    const contents = doc.resolve(pageDict.get('Contents') ?? null) as PdfStream
    expect(contents).toBeInstanceOf(PdfStream)
    expect(latin1(doc.decodeStream(contents))).toContain('0 0 m 100 50 l S')
  })

  it('preserves a multi-level page tree, content arrays, and every P-05 page entry', () => {
    const firstContent = '0 0 m'
    const secondContent = '10 10 l S'
    const metadata = '<?xpacket begin="" id="W5M0MpCehiHzreSzNTczkc9d"?>\n'
      + '<x:xmpmeta xmlns:x="adobe:ns:meta/">\n'
      + '<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">\n'
      + '<rdf:Description rdf:about="" xmlns:test="urn:tsreport:test"><test:page-meta>page-meta</test:page-meta></rdf:Description>\n'
      + '</rdf:RDF>\n</x:xmpmeta>\n<?xpacket end="w"?>'
    const privateData = 'private-layout-state'
    const input = buildBinaryObjectsPdf([
      enc('1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n'),
      enc('2 0 obj\n<< /Type /Pages /Kids [3 0 R 4 0 R] /Count 2 /MediaBox [200 100 0 0] /Rotate 90 /Resources << /ProcSet [/PDF] >> >>\nendobj\n'),
      enc('3 0 obj\n<< /Type /Pages /Parent 2 0 R /Kids [5 0 R] /Count 1 /CropBox [190 90 10 10] /Resources << /ProcSet [/PDF /Text] >> >>\nendobj\n'),
      enc('4 0 obj\n<< /Type /Page /Parent 2 0 R >>\nendobj\n'),
      enc("5 0 obj\n<< /Type /Page /Parent 3 0 R /Rotate 270 /UserUnit 2 /BleedBox [5 5 195 95] /TrimBox [10 10 190 90] /ArtBox [20 20 180 80] /Contents [6 0 R 7 0 R] /Tabs /C /Dur 7.5 /Trans << /Type /Trans /S /Fly /D 2 /Dm /V /M /O /Di /None /SS 0.5 /B true >> /VP [<< /Type /Viewport /BBox [10 10 50 50] /Name (View) >>] /AA << /O << /S /Named /N /NextPage >> /C << /S /Named /N /PrevPage >> >> /Metadata 8 0 R /PieceInfo << /Layout << /LastModified (D:20260713230000+09'00') /Private 9 0 R >> >> /LastModified (D:20260713230000+09'00') >>\nendobj\n"),
      enc(`6 0 obj\n<< /Length ${firstContent.length} >>\nstream\n${firstContent}\nendstream\nendobj\n`),
      enc(`7 0 obj\n<< /Length ${secondContent.length} >>\nstream\n${secondContent}\nendstream\nendobj\n`),
      enc(`8 0 obj\n<< /Type /Metadata /Subtype /XML /Length ${metadata.length} >>\nstream\n${metadata}\nendstream\nendobj\n`),
      enc(`9 0 obj\n<< /Length ${privateData.length} >>\nstream\n${privateData}\nendstream\nendobj\n`),
    ])

    const sourceDoc = parsePdf(input)
    const sourcePages = collectPdfPages(sourceDoc)
    expect(sourcePages).toHaveLength(2)
    expect(sourceDoc.resolve(sourcePages[0]!.resources)).toBeInstanceOf(Map)
    expect(sourceDoc.resolve(sourcePages[0]!.cropBox)).toEqual([190, 90, 10, 10])
    expect(sourceDoc.resolve(sourcePages[1]!.rotate)).toBe(90)

    const merged = mergePdfFiles([input])
    const doc = parsePdf(merged)
    const pages = collectPdfPages(doc)
    expect(pages).toHaveLength(2)
    const page = pages[0]!.dict
    for (const key of ['MediaBox', 'CropBox', 'Resources', 'Rotate', 'UserUnit', 'BleedBox', 'TrimBox', 'ArtBox', 'Contents', 'Tabs', 'Dur', 'Trans', 'VP', 'AA', 'Metadata', 'PieceInfo', 'LastModified']) {
      expect(page.has(key), key).toBe(true)
    }
    expect(doc.resolve(page.get('Contents') ?? null)).toHaveLength(2)
    expect(doc.resolve(page.get('Tabs') ?? null)).toEqual(new PdfName('C'))
    const metadataStream = doc.resolve(page.get('Metadata') ?? null) as PdfStream
    expect(latin1(doc.decodeStream(metadataStream))).toContain(metadata)
    const pieceInfo = doc.resolve(page.get('PieceInfo') ?? null) as Map<string, unknown>
    const layout = doc.resolve(pieceInfo.get('Layout') as PdfRef) as Map<string, unknown>
    const privateStream = doc.resolve(layout.get('Private') as PdfRef) as PdfStream
    expect(latin1(doc.decodeStream(privateStream))).toContain(privateData)

    const importer = PdfImporter.open(merged)
    const imported = importer.importPage(0)
    expect(imported).toMatchObject({ width: 200, height: 400 })
    expect(imported.pageProperties).toMatchObject({
      userUnit: 2,
      rotate: 270,
      contentStreamCount: 2,
      tabs: 'C',
      duration: 7.5,
      transition: { style: 'Fly', direction: 'None', scale: 0.5 },
      viewports: [{ Type: { kind: 'name', value: 'Viewport' } }],
      metadata: { kind: 'stream' },
      pieceInfo: { Layout: { kind: 'dictionary' } },
    })
    expect(imported.pageProperties.boxes).toEqual({
      mediaBox: [0, 0, 200, 400],
      cropBox: [20, 20, 180, 380],
      bleedBox: [10, 10, 190, 390],
      trimBox: [20, 20, 180, 380],
      artBox: [40, 40, 160, 360],
    })

    const secondPage = pages[1]!.dict
    expect(doc.resolve(secondPage.get('Rotate') ?? null)).toBe(90)
    expect(doc.resolve(secondPage.get('MediaBox') ?? null)).toEqual([200, 100, 0, 0])
    expect(secondPage.has('CropBox')).toBe(false)
  })

  it.each([
    ['<< /Type /Pages /Kids [3 0 R] /Count 2 /MediaBox [0 0 10 10] /Resources << >> >>', '<< /Type /Page /Parent 2 0 R >>', /Count.*expected 1/],
    ['<< /Type /Pages /Kids [3 0 R] /Count 1 /MediaBox [0 0 10 10] /Resources << >> >>', '<< /Type /Page /Parent 1 0 R >>', /invalid Parent/],
    ['<< /Type /Pages /Kids [3 0 R] /Count 1 /MediaBox [0 0 10 10] /Resources << >> >>', '<< /Type /Unknown /Parent 2 0 R >>', /Type must be \/Page/],
    ['<< /Type /Pages /Kids [3 0 R] /Count 1 /MediaBox [0 0 10 10] >>', '<< /Type /Page /Parent 2 0 R >>', /valid \/Resources/],
  ])('rejects a malformed page-tree contract: %s', (pagesDictionary, pageDictionary, error) => {
    const pdf = buildBinaryObjectsPdf([
      enc('1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n'),
      enc(`2 0 obj\n${pagesDictionary}\nendobj\n`),
      enc(`3 0 obj\n${pageDictionary}\nendobj\n`),
    ])
    expect(() => collectPdfPages(parsePdf(pdf))).toThrow(error)
  })

  // Verifies that the /Prev xref chain is followed so the newest incremental update wins over the original object.
  it('incremental update (Prev チェーン) で最新の更新が反映される', () => {
    const input = buildIncrementalUpdatePdf()
    const merged = mergePdfFiles([input])

    const text = pdfToText(merged)
    expect(text).toContain('0 0 1 RG') // updated revision
    expect(text).not.toContain('1 0 0 RG') // the initial revision has been replaced

    const doc = parsePdf(merged)
    expect(collectPdfPages(doc).length).toBe(1)
  })

  // Verifies that an encrypted PDF still rejects when the caller does not provide the password.
  it('暗号化 PDF はパスワード未指定なら明確なエラーを投げる', () => {
    const encrypted = makeEncryptedTextPdf('rc4-128')

    expect(() => mergePdfFiles([encrypted])).toThrow(/password/)
  })

  it.each(['rc4-128', 'aes-128', 'aes-256'] as const)(
    '暗号化 PDF (%s) をパスワード付きで解析できる',
    (method) => {
      const encrypted = makeEncryptedTextPdf(method)
      const doc = parsePdf(encrypted, { password: 'secret' })
      const pages = collectPdfPages(doc)
      expect(pages.length).toBe(1)
      const contents = doc.resolve(pages[0]!.dict.get('Contents') ?? null) as PdfStream
      const decoded = latin1(doc.decodeStream(contents))
      expect(decoded).toContain('BT')
      expect(decoded).toContain('Tj')
      expect(decoded).toContain(' m')
      expect(decoded).toContain(' l')
    },
  )

  it('カスタム名の Crypt filter stream を復号できる', () => {
    const doc = parsePdf(makeCustomCryptFilterPdf(), { password: 'secret' })
    const pages = collectPdfPages(doc)
    expect(pages.length).toBe(1)
    const contents = doc.resolve(pages[0]!.dict.get('Contents') ?? null)
    expect(contents).toBeInstanceOf(PdfStream)
    const decoded = latin1(doc.decodeStream(contents as PdfStream))
    expect(decoded).toContain('0 0 m 100 50 l S')
  })

  it('TIFF predictor 2 stream を packed bit/16-bit 成分でも復号できる', () => {
    const packed1Bit = parsePdf(buildTiffPredictorContentPdf(
      new Uint8Array([0xEB]),
      { colors: 1, bitsPerComponent: 1, columns: 8 },
    ))
    const packed1BitContents = packed1Bit.resolve(collectPdfPages(packed1Bit)[0]!.dict.get('Contents') ?? null) as PdfStream
    expect(packed1Bit.decodeStream(packed1BitContents)).toEqual(new Uint8Array([0xB2]))

    const packed4Bit = parsePdf(buildTiffPredictorContentPdf(
      new Uint8Array([0x12, 0x4B]),
      { colors: 1, bitsPerComponent: 4, columns: 4 },
    ))
    const packed4BitContents = packed4Bit.resolve(collectPdfPages(packed4Bit)[0]!.dict.get('Contents') ?? null) as PdfStream
    expect(packed4Bit.decodeStream(packed4BitContents)).toEqual(new Uint8Array([0x13, 0x72]))

    const sixteenBit = parsePdf(buildTiffPredictorContentPdf(
      new Uint8Array([0x01, 0x00, 0x00, 0x02, 0xFE, 0xFF]),
      { colors: 1, bitsPerComponent: 16, columns: 3 },
    ))
    const sixteenBitContents = sixteenBit.resolve(collectPdfPages(sixteenBit)[0]!.dict.get('Contents') ?? null) as PdfStream
    expect(sixteenBit.decodeStream(sixteenBitContents)).toEqual(new Uint8Array([0x01, 0x00, 0x01, 0x02, 0x00, 0x01]))
  })

  it('PNG predictor の切り詰められた最終rowを拒否する', () => {
    const doc = parsePdf(buildPngPredictorContentPdf(new Uint8Array([0, 1, 2]), 3))
    const contents = doc.resolve(collectPdfPages(doc)[0]!.dict.get('Contents') ?? null) as PdfStream
    expect(() => doc.decodeStream(contents)).toThrow('partial row')
  })

  it('LZWDecode EarlyChange 0/1 の辞書サイズ境界を復号できる', () => {
    const plain = new Uint8Array(2048)
    for (let i = 0; i < plain.length; i++) plain[i] = (i * 37 + (i >> 3)) & 0xFF

    const earlyChangeOneDoc = parsePdf(buildLzwContentPdf(
      lzwEncode(plain, 1),
      '/DecodeParms << /EarlyChange 1 >>',
    ))
    const earlyChangeOneContents = earlyChangeOneDoc.resolve(collectPdfPages(earlyChangeOneDoc)[0]!.dict.get('Contents') ?? null) as PdfStream
    expect(earlyChangeOneDoc.decodeStream(earlyChangeOneContents)).toEqual(plain)

    const earlyChangeZeroDoc = parsePdf(buildLzwContentPdf(
      lzwEncode(plain, 0),
      '/DecodeParms << /EarlyChange 0 >>',
    ))
    const earlyChangeZeroContents = earlyChangeZeroDoc.resolve(collectPdfPages(earlyChangeZeroDoc)[0]!.dict.get('Contents') ?? null) as PdfStream
    expect(earlyChangeZeroDoc.decodeStream(earlyChangeZeroContents)).toEqual(plain)
  })

  it('LZWDecode EarlyChange の無効値を拒否する', () => {
    const encoded = lzwEncode(enc('abc'), 1)

    const outOfRangeDoc = parsePdf(buildLzwContentPdf(encoded, '/DecodeParms << /EarlyChange 2 >>'))
    const outOfRangeContents = outOfRangeDoc.resolve(collectPdfPages(outOfRangeDoc)[0]!.dict.get('Contents') ?? null) as PdfStream
    expect(() => outOfRangeDoc.decodeStream(outOfRangeContents)).toThrow(/EarlyChange/)

    const nonIntegerDoc = parsePdf(buildLzwContentPdf(encoded, '/DecodeParms << /EarlyChange 0.5 >>'))
    const nonIntegerContents = nonIntegerDoc.resolve(collectPdfPages(nonIntegerDoc)[0]!.dict.get('Contents') ?? null) as PdfStream
    expect(() => nonIntegerDoc.decodeStream(nonIntegerContents)).toThrow(/EarlyChange/)

    const wrongTypeDoc = parsePdf(buildLzwContentPdf(encoded, '/DecodeParms << /EarlyChange /One >>'))
    const wrongTypeContents = wrongTypeDoc.resolve(collectPdfPages(wrongTypeDoc)[0]!.dict.get('Contents') ?? null) as PdfStream
    expect(() => wrongTypeDoc.decodeStream(wrongTypeContents)).toThrow(/EarlyChange/)
  })

  it.each(['rc4-128', 'aes-128', 'aes-256'] as const)(
    '暗号化 PDF (%s) をパスワード付きでマージできる',
    (method) => {
      const encrypted = makeEncryptedTextPdf(method)
      const merged = mergePdfFiles([encrypted], { password: 'secret' })
      const doc = parsePdf(merged)
      const pages = collectPdfPages(doc)
      expect(pages.length).toBe(1)
      const contents = doc.resolve(pages[0]!.dict.get('Contents') ?? null) as PdfStream
      const decoded = latin1(doc.decodeStream(contents))
      expect(decoded).toContain('BT')
      expect(decoded).toContain('Tj')
    },
  )

  it('入力ごとに異なる暗号化 PDF パスワードを指定してマージできる', () => {
    const a = makeEncryptedTextPdf('rc4-128')
    const b = makeTextPdf()
    const merged = mergePdfFiles([a, b], { passwords: ['secret', ''] })
    const doc = parsePdf(merged)
    expect(collectPdfPages(doc).length).toBe(3)
  })

  // Verifies that a merged output can itself be merged again and its content streams stay decodable.
  it('ラウンドトリップ: マージ結果を再度マージできる', () => {
    const merged = mergePdfFiles([makeTextPdf(), makeImagePdf()])
    const remerged = mergePdfFiles([merged, makeClassicXrefPdf()])

    const doc = parsePdf(remerged)
    const pages = collectPdfPages(doc)
    expect(pages.length).toBe(4)

    // Decode the first page's content stream and confirm text drawing
    const contents = doc.resolve(pages[0]!.dict.get('Contents') ?? null) as PdfStream
    const decoded = latin1(doc.decodeStream(contents))
    expect(decoded).toContain('BT')
    expect(decoded).toContain('Tj')
  })

  // Verifies that merging an empty input list throws a "no input" error.
  it('入力が空の場合はエラー', () => {
    expect(() => mergePdfFiles([])).toThrow(/no input/)
  })
})
